TT#71608 Port ec2-tools from ec2-api-tools to awscli
Change-Id: I147c8a6c2ae1fca4e680df8d2fde170b2f33f856

diff --git a/ec2-publish-ami b/ec2-publish-ami
--- a/ec2-publish-ami
+++ b/ec2-publish-ami
@@ -1,14 +1,6 @@
 #!/bin/bash
 
-export EC2_HOME="/usr/share/ec2/ec2-api-tools"
-export JAVA_HOME="$(dirname $(dirname $(readlink /etc/alternatives/java)))"
-export PATH="$PATH:${EC2_HOME}/bin"
 export TZ="UTC"
-
-# retrieve AWS_* environment variables
-if [ -r "$HOME/.ec2-create-ngcp" ] ; then
-  source "$HOME/.ec2-create-ngcp"
-fi
 
 usage() {
   echo "$0 - script to mark a specified EC2 AMI as public
@@ -28,12 +20,12 @@ Supported OPTIONS:
 
 CMDLINE_OPTS=ami:,help,region:
 
-_opt_temp=$(getopt --name $0 -o +bch --long $CMDLINE_OPTS -- "$@")
+_opt_temp=$(getopt --name $0 -o +bch --long ${CMDLINE_OPTS} -- "$@")
 if [ $? -ne 0 ]; then
   echo "Try '$0 --help' for more information." >& 2
   exit 1
 fi
-eval set -- "$_opt_temp"
+eval set -- "${_opt_temp}"
 
 _opt_public=false
 
@@ -60,42 +52,32 @@ while :; do
 done
 
 # if unset set sane defaults
-[ -n "$AWS_REGION" ] || AWS_REGION="eu-west-1"
-
-if [ -z "$AWS_ACCESS_KEY" ] ; then
-  echo "AWS_ACCESS_KEY is unset, can not continue." >&2
-  exit 1
-fi
-
-if [ -z "$AWS_SECRET_KEY" ] ; then
-  echo "AWS_SECRET_KEY is unset, can not continue." >&2
-  exit 1
-fi
+[ -n "${AWS_REGION}" ] || AWS_REGION="eu-west-1"
 
 check4progs(){
   local RC=''
   for arg in $* ; do
-    which $arg >/dev/null 2>&1 || RC="$arg"
+    which ${arg} >/dev/null 2>&1 || RC="${arg}"
   done
-  if [ -n "$RC" ] ; then
-    echo "$RC not found/executable" >&2
+  if [ -n "${RC}" ] ; then
+    echo "${RC} not found/executable" >&2
     return 1
   fi
 }
 
-if ! check4progs ec2-modify-image-attribute ; then
-  echo "Required tools not found, forgot to install ec2-api-tools?" >&2
+if ! check4progs aws ; then
+  echo "Required tool aws not found, forgot to install awscli?" >&2
   exit 1
 fi
 
-if [ -z "$AMI_ID" ] ; then
+if [ -z "${AMI_ID}" ] ; then
   usage >&2
   exit 1
 fi
 
-echo "Marking AMI $AMI_ID as public"
-ec2-modify-image-attribute --region "$AWS_REGION" "$AMI_ID" --launch-permission -a all
+echo "Marking AMI ${AMI_ID} as public"
+aws ec2 modify-image-attribute --region "${AWS_REGION}" --image-id "${AMI_ID}" --launch-permission "Add=[{Group=all}]"
 if [ $? -ne 0 ] ; then
-  echo "Noticed problem when trying to mark AMI with ID $AMI_ID as public." >&2
+  echo "Noticed problem when trying to mark AMI with ID ${AMI_ID} as public." >&2
   exit 1
 fi
