Check for availability through ssh login

diff --git a/ec2-create-ce b/ec2-create-ce
--- a/ec2-create-ce
+++ b/ec2-create-ce
@@ -250,6 +250,20 @@ else
 
   # we probably have a new hostname after reboot
   HOSTNAME="$(ec2-describe-instances --region ${AWS_REGION} --filter instance-id=$INSTANCE_ID | awk '/INSTANCE/ {print $4}')"
+
+  # now check for available ssh connection
+  retry=120 # up to 10 minutes
+  STATUS=""
+  while [ "$STATUS" != "ok" ] && [ $retry -ne 0 ] ; do
+    ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i "${KEY_FILE}" "admin@$HOSTNAME" "cat /etc/motd"
+    if [ $? -eq 0 ] ; then
+      STATUS=ok
+    else
+      echo "Host $HOSTNAME can't be reached via ssh login yet, checking again in 5 seconds ($retry retries left)."
+      sleep 5
+      retry=$(($retry - 1))
+    fi
+  done
 fi
 
 
